### ISSUE TITLE
username and login not parsed

### ISSUE THREAD

**Issue by hermannsblum** [martinhoefling/gopassbridge#13]
My pass github.com entry looks as following

```
password
username: hermannsblum
login: hermannsblum
```

I tried all combinations of only username, username and login etc. gopassbridge will never fill in the username in the github.com login form, only the password.
The same record is actually parsed correctly by passforios, so I guess there is no encoding error and this is really an issue of this addon.
I tried gopass-bridge on chrome and firefox, same issue with both.

**Comment by martinhoefling** [comment]
gopassbridge uses the provided information from gopass and gopass itself makes use of yaml data. However, the yaml data must be separated by `---` from the first line.

So, your entry should look like:
```
password
---
username: hermannsblum
login: hermannsblum
```

`gopass fix` can do this conversion for you as far as I know.

**Comment by hermannsblum** [comment]
Thanks for pointing that out, I submitted a PR to the gopass team to clarify this in their documentation 👍
