### ISSUE TITLE
hidden passwordfield selected instead of visible passwordfield

### ISSUE THREAD

**Issue by mjrider** [martinhoefling/gopassbridge#14]
Hello,
This is an enhancement request, because some banks, like ING, are actively trying to stop users from using a password manager.

End result, the hidden passsword field gets selected instead of the 'real' password field.

A solution could be ranking password fields based on a list of tests, and pick the first field with a good ranking. Such as the first visible password field, which is below the login field, and has a higher tabindex then the login field

the tricks used by  ING:
- tabindex=-1
- parent element has a size of 0
- password field has no name/id

```html
<div style="width:0px;height:0px;overflow:hidden;">
  <input tabindex="-1" type="password">
</div>
```

login page: https://mijn.ing.nl/internetbankieren/SesamLoginServlet

**Comment by martinhoefling** [comment]
Hey @mjrider, thx for the example. We already discard hidden inputs but this is an input in a hidden div. We need to find a solution for this. The best starting point would be if we could start with a (failing) test using the page source. I'll try this out first. Maybe we can filter fields in invisible elements?

**Comment by martinhoefling** [comment]
Wow, I looked a bit at the js. That's dirty :-) . So we select the login input based on the focus. how about selecting the password with a larger tabindex?

**Comment by martinhoefling** [comment]
https://github.com/martinhoefling/gopassbridge/tree/ing-nl

**Comment by martinhoefling** [comment]
Can you test pr #15?
