### ISSUE TITLE
Chrome extention generates error in console

### ISSUE THREAD

**Issue by mjrider** [martinhoefling/gopassbridge#16]
gopass bridge gives an error in the console of the developer tools with version v0.2.1

```
Uncaught ReferenceError: module is not defined
    at content.js:272
```
this is located at https://github.com/martinhoefling/gopassbridge/blob/v0.2.1/web-extension/content.js#L272

expected behaviour would be that the chrome extension doesn't generate a javascript error on every page load

**Comment by martinhoefling** [comment]
Oh, that got introduced with the testsuite for content.js as I did not find another solution to hook in the content.js code into jest / jsdom. Strangely it only occurs on chrome and not ffx. I'll take a look at it.
