### ISSUE TITLE
Multiple stores

### ISSUE THREAD

**Issue by zsau** [martinhoefling/gopassbridge#18]
Support for multiple stores (e.g. 'work' and 'personal') would be great. Rough sketch/brainstorm: an addon pref that holds one or more path-plus-nickname entries, together with some right-justified text in the toolbar popup that shows the nickname of the store each entry belongs to (when more than one store is configured). How does that sound?

**Comment by martinhoefling** [comment]
Not sure how you mean that. Gopass supports multiple stores via mounts. So you can mount your personal and work store and have personal/github.com and work/github.com displayed as suggestion. 
Can you explain a bit more your idea?

**Comment by zsau** [comment]
Huh, I'd totally forgotten about the mounts feature. I was never able to get it working before due to confusing instructions, but it's working now and it's just what I wanted. Thanks!

**Comment by martinhoefling** [comment]
Awesome! I just prefer to keep the browser interface as simple as possible and use gopass features whenever possible. I’m glad that you could make it work.
