### ISSUE TITLE
Use <Enter> to fill in only match

### ISSUE THREAD

**Issue by robinro** [martinhoefling/gopassbridge#32]
When there is only one matching entry (either on initial open or after a search), pressing enter in the search field should accept that entry.

This would simplify the default usecase via keyboard to:
* ctrl-U, (check the correct entry is selected), Enter

**Comment by martinhoefling** [comment]
Ah, no you mean pressing enter in the search? Or focusing the first entry automatically (that would defocus the search field and feel a bit strange)

**Comment by martinhoefling** [comment]
I tried listening on the enter event in the input field, but it does not work for me here (FFX59)
