### ISSUE TITLE
Uncaught ReferenceError: getSyncStorage is not defined

### ISSUE THREAD

**Issue by mjrider** [martinhoefling/gopassbridge#7]
like the subject, this is the error i get when i load a random website,

the first lines of content.js are:

```js
'use strict';

var browser = browser || chrome;

var options = null;

getSyncStorage(function (result) {
    options = result;
}, function () {
    alert('Could not read config options');
});
```

**Comment by mjrider** [comment]
it seems that generic.js is not loaded when the extension is loading content.js

**Comment by martinhoefling** [comment]
Which version and which browser are you using?

**Comment by martinhoefling** [comment]
Ah yeah, this is the newest one. I'll fix this right away.

**Comment by martinhoefling** [comment]
v0.1.1 released
