### ISSUE TITLE
Does not match when pass entry has extra info after domain

### ISSUE THREAD

**Issue by wezm** [martinhoefling/gopassbridge#8]
For some domains I have more that one account. To store them in pass they have a suffix. E.g. for Twitter I have:

- twitter.com (wezm)
- twitter.com (BinaryTranceSW)
- twitter.com (SymbolMate)

When I click on the the gopassbridge icon in Firefox it says, "no results for twitter.com". The expected behaviour is it would list all entries that contain twitter.com. Note that browserpass behaves this way, correctly listing them all.

**Comment by martinhoefling** [comment]
You can use / instead of a suffix. E.g:

```
Accounts/twitter.com/myaccount
Accounts/twitter.com/anotheraccount
```

Does this help?

**Comment by martinhoefling** [comment]
Btw. this is a security feature. Gopassbridge uses separate searches for automatic host search and user input to prevent tricking the user into filling in a (partially) matching password. For more details, have a look at the [respondHostQuery](https://github.com/justwatchcom/gopass/blob/master/utils/jsonapi/responses.go#L42) function in gopass. It is also taken care of public suffixes.

**Comment by wezm** [comment]
> You can use / instead of a suffix.
I wondered if that was the right way to do it. I imported all my passwords from my previous password manager so stuck with the previous convention. I have over 1400 items so it's going to take a bit to reorganise them all.

**Comment by martinhoefling** [comment]
@wezm understood. However, I would not make a security compromise here by default. Since we do not want to unencrypt all secrets with pass/gopass during search (slow), the name / path is the only option to store the URL.

One option to solve this issue for you would be a switch (option) to use the normal search instead of host based search but I wouldn't enable that by default. This however would only work with exactly matching domains in your path. Would that solve your issue?

**Comment by wezm** [comment]
>  Since we do not want to unencrypt all secrets with pass/gopass during search (slow), the name / path is the only option to store the URL.

To clarify, "twitter.com (wezm)", is the name of the item. I.e. the unencryped data. I agree that you shouldn't be unecrypting en-masse. Basically all I need for this to work is do a partial match on the unencrypted item name instead of exact match — no need to decrypt anything until an item is selected for autofill.

**Comment by martinhoefling** [comment]
Yes, but if the hostname is `login.twitter.com` the search will not match. This is what `queryHost` does.
